---
title: "AGDQ 2019"
date: "`r format(Sys.time(), '%F %T %Z')`"
output: html_document
---

```{r setup, include=FALSE}
source("helpers.R")
opts_chunk$set(fig.path = "plots/agdq2019_")
p_title <- "Awesome Games Done Quick 2019: Donation Breakdown"

agdq <- readRDS("data/agdq2019.rds") %>%
  filter(between(time, 
                 filter(event_dates, event == "AGDQ2019")$start, 
                 filter(event_dates, event == "AGDQ2019")$end)) %>%
  arrange(time) %>%
  mutate(day_num = fct_inorder(as.character(day_num), ordered = TRUE))
```

Donation timeline:

```{r timeline}
agdq %>%
  ggplot(data = ., aes(x = time, y = cumsum(amount))) +
  geom_line(size = 2) +
  scale_x_datetime(date_breaks = "24 hours",
                   date_labels = "%a (%d.)",
                   date_minor_breaks = "6 hours") +
  scale_y_continuous(breaks = seq(0, 3e6, 2.5 * 10^5),
                     labels = scales::dollar,
                     sec.axis = dup_axis(~.*0.88,
                                         labels = euro_scale,
                                         breaks = seq(0, 3e6, 25e4))) +
  labs(title = p_title, caption = p_caption,
       subtitle = "Cumulative donations over the course of the event, all times in UTC.",
       x = "Time", y = "Amount Total") +
  theme_ipsum_rc(grid = "XY")
```
